FROM nginx:latest
COPY /Users/matsumotoyuison/MyApplication/todo2020/springdemo_k8s/src/main/resources/static/css /usr/share/nginx/html/css
COPY /Users/matsumotoyuison/MyApplication/todo2020/springdemo_k8s/src/main/resources/static/js /usr/share/nginx/html/js
COPY /Users/matsumotoyuison/MyApplication/todo2020/springdemo_k8s/src/main/resources/static/img /usr/share/nginx/html/img